[build]
  # Directorio de publicación (raíz del proyecto)
  publish = "."
  
  # Comando de build (no necesario para sitio estático)
  command = "echo 'No build required for static site'"

[build.environment]
  # Variables de entorno para el build
  NODE_VERSION = "18"

# Configuración de redirects y rewrites
[[redirects]]
  # Redirect para admin sin extensión
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  # Redirect para test sin extensión
  from = "/test"
  to = "/test-productos.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad básica
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache para recursos estáticos
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    # Cache más corto para HTML
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/admin.html"
  [headers.values]
    # Headers adicionales de seguridad para admin
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Configuración de formularios (si se necesita en el futuro)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

# Configuración de funciones (para futuras mejoras)
[functions]
  directory = "netlify/functions"